export const CAMPAIGN = Object.freeze({
  name: "IRON LEDGER // SIXFOLD",
  shortName: "SIXFOLD",
  subtitle: "Six missions. Sixteen weeks. Every rep accounted for.",
  start: "2026-09-07",
  trainingEnd: "2026-12-27",
  summitStart: "2026-12-28",
  target: "2026-12-31",
  totalWeeks: 16,
  timezone: "local",
});

export const GOALS = Object.freeze([
  {
    id: "incline",
    order: 1,
    family: "press",
    name: "30° Incline Bench",
    short: "INCLINE",
    targetText: "250 × 8",
    unit: "lb",
    type: "strength",
    baseline: { load: 215, reps: 8, rpe: 9, date: CAMPAIGN.start },
    target: { load: 250, reps: 8 },
    deltaText: "+35 lb at the same 8 reps",
    standard: "Bench fixed at 30°, controlled touch, no bounce, full lockout, one uninterrupted set.",
    why: "Two weekly exposures pair high-force practice with enough submaximal volume to build upper-pec and triceps capacity without turning every session into a test.",
    medals: [
      { tier: "Bronze", load: 225, reps: 8, label: "225 × 8" },
      { tier: "Silver", load: 240, reps: 8, label: "240 × 8" },
      { tier: "Gold", load: 250, reps: 8, label: "250 × 8" },
    ],
  },
  {
    id: "ohp",
    order: 2,
    family: "press",
    name: "Strict Seated Overhead Press",
    short: "OHP",
    targetText: "185 × 5",
    unit: "lb",
    type: "strength",
    baseline: { load: 155, reps: 8, rpe: 8, date: CAMPAIGN.start },
    target: { load: 185, reps: 5 },
    deltaText: "+30 lb on the bar; preserve strict form",
    standard: "Seated, no leg drive, controlled lower, full overhead lockout without lumbar overextension.",
    why: "A strict vertical press creates a legitimate shoulder-strength target while incline pressing supplies additional anterior-delt and triceps volume.",
    medals: [
      { tier: "Bronze", load: 165, reps: 8, label: "165 × 8" },
      { tier: "Silver", load: 175, reps: 6, label: "175 × 6" },
      { tier: "Gold", load: 185, reps: 5, label: "185 × 5" },
    ],
  },
  {
    id: "chin",
    order: 3,
    family: "pull",
    name: "Weighted Chin-Up",
    short: "+CHIN",
    targetText: "+130 × 6",
    unit: "lb added",
    type: "strength",
    baseline: { load: 90, reps: 8, rpe: 7, bodyweight: 205, date: CAMPAIGN.start },
    target: { load: 130, reps: 6 },
    deltaText: "+40 lb external load",
    standard: "Dead hang start, no kip, chin clearly over bar, controlled return to full elbow extension.",
    why: "Heavy low-rep practice raises peak pulling strength; the medium day adds clean volume without colliding with the separate pull-up-density goal.",
    medals: [
      { tier: "Bronze", load: 105, reps: 8, label: "+105 × 8" },
      { tier: "Silver", load: 120, reps: 6, label: "+120 × 6" },
      { tier: "Gold", load: 130, reps: 6, label: "+130 × 6" },
    ],
  },
  {
    id: "pullups",
    order: 4,
    family: "pull",
    name: "Pull-Up Hour",
    short: "PULL/HOUR",
    targetText: "500 / 60 min",
    unit: "strict reps",
    type: "endurance",
    baseline: { total: 75, duration: 10, maxSet: 30, date: CAMPAIGN.start },
    target: { total: 500, duration: 60 },
    deltaText: "+425 reps and +50 sustained minutes",
    standard: "Every rep begins at full extension and finishes chin over bar; no kipping. The clock runs continuously for 60 minutes.",
    why: "Density progresses by total work and sustained duration. Shorter efforts are never extrapolated into an earned hour result, protecting the meaning of the goal.",
    medals: [
      { tier: "Bronze", total: 300, duration: 60, label: "300 / 60 min" },
      { tier: "Silver", total: 400, duration: 60, label: "400 / 60 min" },
      { tier: "Gold", total: 500, duration: 60, label: "500 / 60 min" },
    ],
  },
  {
    id: "curl",
    order: 5,
    family: "pull",
    name: "Wall-Strict EZ Curl",
    short: "CURL",
    targetText: "135 × 5",
    unit: "lb",
    type: "strength",
    baseline: { load: 100, reps: 10, rpe: 10, date: CAMPAIGN.start },
    target: { load: 135, reps: 5 },
    deltaText: "+35 lb with zero body English",
    standard: "Head, upper back, and hips against wall; elbows stay quiet; full controlled range; no hip drive.",
    why: "Direct elbow-flexor work is distributed over heavy and medium pull days so the biceps and brachialis grow without one giant elbow-hostile dose.",
    medals: [
      { tier: "Bronze", load: 115, reps: 8, label: "115 × 8" },
      { tier: "Silver", load: 125, reps: 6, label: "125 × 6" },
      { tier: "Gold", load: 135, reps: 5, label: "135 × 5" },
    ],
  },
  {
    id: "squat",
    order: 6,
    family: "lower",
    name: "Pain-Controlled Squat",
    short: "SQUAT",
    targetText: "200 × 10",
    unit: "lb",
    type: "strength",
    baseline: null,
    target: { load: 200, reps: 10 },
    deltaText: "Baseline set by first clean, cleared Week 1 assessment",
    standard: "Clinician-cleared variation and range, controlled descent, stable mechanics, pain within your approved limit during and the following day.",
    why: "This is a tolerance-first progression. Load only advances when technique and the 24-hour symptom response are acceptable; pain is never a price of admission.",
    medals: [
      { tier: "Bronze", load: 135, reps: 10, label: "135 × 10" },
      { tier: "Silver", load: 165, reps: 10, label: "165 × 10" },
      { tier: "Gold", load: 200, reps: 10, label: "200 × 10" },
    ],
  },
]);

export const PHASES = Object.freeze([
  { id: "foundation", name: "Foundation", weeks: [1, 2, 3], purpose: "Own the standards, establish squat tolerance, and accumulate high-quality work below failure." },
  { id: "deload-1", name: "Deload", weeks: [4], purpose: "Cut fatigue while retaining movement exposure." },
  { id: "strength", name: "Strength", weeks: [5, 6, 7], purpose: "Raise force output with heavier top sets and disciplined backoffs." },
  { id: "deload-2", name: "Deload", weeks: [8], purpose: "Absorb the first loading block and protect joints." },
  { id: "specificity", name: "Specificity", weeks: [9, 10, 11], purpose: "Practice closer to target loads and extend pull-up density." },
  { id: "deload-3", name: "Deload", weeks: [12], purpose: "Reduce volume before the final realization block." },
  { id: "realization", name: "Realization", weeks: [13, 14], purpose: "Convert accumulated strength into target-pattern performance." },
  { id: "taper", name: "Taper", weeks: [15, 16], purpose: "Preserve intensity, shed fatigue, and arrive fresh for Summit Week." },
]);

export const WEEK_INTENT = Object.freeze([
  { week: 1, load: 0.00, volume: 1.00, topReps: 6, label: "Standards + squat baseline" },
  { week: 2, load: 0.08, volume: 1.04, topReps: 6, label: "Build repeatability" },
  { week: 3, load: 0.16, volume: 1.08, topReps: 5, label: "First overload" },
  { week: 4, load: 0.08, volume: 0.58, topReps: 5, label: "Deload 1" },
  { week: 5, load: 0.28, volume: 1.00, topReps: 5, label: "Strength block opens" },
  { week: 6, load: 0.38, volume: 1.04, topReps: 5, label: "Heavy accumulation" },
  { week: 7, load: 0.48, volume: 1.06, topReps: 4, label: "Strength checkpoint" },
  { week: 8, load: 0.30, volume: 0.56, topReps: 5, label: "Deload 2" },
  { week: 9, load: 0.58, volume: 0.96, topReps: 5, label: "Specificity opens" },
  { week: 10, load: 0.68, volume: 1.00, topReps: 4, label: "Target-pattern work" },
  { week: 11, load: 0.78, volume: 0.96, topReps: 4, label: "Specificity checkpoint" },
  { week: 12, load: 0.46, volume: 0.52, topReps: 5, label: "Deload 3" },
  { week: 13, load: 0.88, volume: 0.82, topReps: 4, label: "Realization" },
  { week: 14, load: 0.96, volume: 0.72, topReps: 3, label: "Peak exposure" },
  { week: 15, load: 0.72, volume: 0.48, topReps: 3, label: "Taper: sharpen" },
  { week: 16, load: 0.48, volume: 0.34, topReps: 3, label: "Taper: arrive fresh" },
]);

export const PULLUP_DENSITY = Object.freeze([
  { week: 1, reps: 5, minutes: 20 },
  { week: 2, reps: 5, minutes: 24 },
  { week: 3, reps: 6, minutes: 20 },
  { week: 4, reps: 4, minutes: 15 },
  { week: 5, reps: 6, minutes: 24 },
  { week: 6, reps: 6, minutes: 28 },
  { week: 7, reps: 7, minutes: 24 },
  { week: 8, reps: 5, minutes: 20 },
  { week: 9, reps: 7, minutes: 30 },
  { week: 10, reps: 7, minutes: 36 },
  { week: 11, reps: 8, minutes: 32 },
  { week: 12, reps: 6, minutes: 24 },
  { week: 13, reps: 8, minutes: 40 },
  { week: 14, reps: 8, minutes: 50 },
  { week: 15, reps: 6, minutes: 30 },
  { week: 16, reps: 8, minutes: 20 },
]);

export const SESSION_DAYS = Object.freeze({
  1: { key: "heavy-press", name: "Heavy Press + Medium Squat", code: "HP+MS", theme: "PRESS / FORCE", duration: "70–90 min", focus: "Low-volume force production, then controlled squat practice." },
  2: { key: "heavy-pull", name: "Heavy Pull", code: "HPULL", theme: "PULL / FORCE", duration: "60–75 min", focus: "Weighted chin and curl strength with upper-back support." },
  4: { key: "heavy-squat", name: "Heavy Squat + Medium Press", code: "HS+MP", theme: "LOWER / PRESS", duration: "75–95 min", focus: "Pain-controlled squat loading plus submaximal press volume." },
  6: { key: "medium-pull", name: "Medium Pull + Density", code: "MPULL", theme: "PULL / ENGINE", duration: "60–110 min", focus: "Volume, strict pull-up economy, grip and elbow durability. Duration rises with the density block." },
});

export const SUMMIT = Object.freeze({
  "2026-12-28": { key: "summit-press", name: "Summit I · Press", code: "TEST", duration: "45–70 min", focus: "Incline and overhead Gold attempts. Full recovery between attempts." },
  "2026-12-29": { key: "summit-squat", name: "Summit II · Squat", code: "TEST", duration: "30–45 min", focus: "Only attempt the pain-controlled standard if readiness and symptoms are acceptable." },
  "2026-12-30": { key: "summit-pull", name: "Summit III · Strength Pull", code: "TEST", duration: "45–60 min", focus: "Weighted chin and wall-strict curl Gold attempts." },
  "2026-12-31": { key: "summit-hour", name: "Summit IV · Pull-Up Hour", code: "TEST", duration: "75–90 min", focus: "500 strict reps in 60 continuous minutes: alternate 8 and 9 reps each minute." },
});

// Reward text is intentionally encoded so the ordinary interface can preserve the surprise.
// A static client cannot make a secret cryptographically inaccessible to a determined source-code reader.
export const CACHE_VAULT = Object.freeze([
  [1, 150, "QWx0cmEgdHJhaWwvaGlraW5nIHNob2VzIOKAlCBFeHBlcmllbmNlIFdpbGQgMyBzaG9ydGxpc3Q=", "Rml0IGFuZCBjbGluaWNpYW4gZ3VpZGFuY2UgZ292ZXJuLiBBIG51cnNlIGRpc2NvdW50IGlzIG5vdCBhc3N1bWVkLg=="],
  [2, 25, "RnJhY3Rpb25hbCBwbGF0ZXMgLyBtaWNyb2xvYWRpbmc=", "U21hbGxlciBqdW1wcyBtYWtlIHByZXNzIGFuZCBjdXJsIHByb2dyZXNzaW9uIG1vcmUgcHJlY2lzZS4="],
  [3, 25, "UHJlbWl1bSBzbGVlcCBtYXNr", "U3VwcG9ydHMgZGF5dGltZSBzbGVlcCBxdWFsaXR5IGFyb3VuZCBzaGlmdCB3b3JrLg=="],
  [4, 50, "V2hpdGUtbm9pc2UgLyBkYXl0aW1lIHNvdW5kIGJsb2NrZXI=", "Q3JlYXRlcyBhIG1vcmUgcmVwZWF0YWJsZSBzbGVlcCBlbnZpcm9ubWVudC4="],
  [5, 25, "Rm9vZCBzY2FsZSArIHNoaWZ0IGNvbnRhaW5lcnM=", "TWFrZXMgdGhlIDE3MCBnIHByb3RlaW4gZmxvb3IgZWFzaWVyIHRvIGhpdCBvbiBidXN5IGRheXMu"],
  [6, 50, "QmxhY2tvdXQgcm9vbSB1cGdyYWRl", "UmVkdWNlcyBsaWdodCBpbnRydXNpb24gZm9yIGRheXRpbWUgc2xlZXAu"],
  [7, 25, "UmVzaXN0YW5jZSAvIGFzc2lzdCBiYW5kcw==", "U2NhbGVzIHB1bGwtdXAgdm9sdW1lIGFuZCBnaXZlcyB5b3UgYSBqb2ludC1mcmllbmRseSBzdWJzdGl0dXRlLi"],
  [8, 100, "VHJla2tpbmcgcG9sZXM=", "U3VwcG9ydHMgbG9uZ2VyIG91dGRvb3IgZGF5cyBhbmQgY2FuIHJlZHVjZSBsb3dlci1ib2R5IGxvYWQgZGVtYW5kcy4="],
  [9, 25, "V3Jpc3QtbmV1dHJhbCByb3RhdGluZyBwdWxsaW5nIGhhbmRsZSBmdW5k", "QSBwb3RlbnRpYWxseSBtb3JlIGNvbWZvcnRhYmxlIG9wdGlvbiBmb3IgaGlnaC1yZXAgcHVsbGluZy4="],
  [10, 50, "SG91c2UgY2xlYW5pbmcgLyBtZWFsLWhlbHAgZnVuZA==", "QnV5cyBiYWNrIHRpbWUgYW5kIHJlZHVjZXMgZnJpY3Rpb24gYXJvdW5kIHJlY292ZXJ5Li"],
  [11, 50, "Q2xpbmljaWFuLWFwcHJvdmVkIHJlY292ZXJ5IHNlc3Npb24gLyBzcG9ydHMgbWFzc2FnZQ==", "T25seSBpZiBhcHByb3ByaWF0ZSBmb3IgeW91ciBoaXN0b3J5IGFuZCBjdXJyZW50IHN5bXB0b21zLi"],
  [12, 100, "QUFDTiBFQ0NPIC8gQ0NSTiBmdW5k", "QSBjYXJlZXItY2FwaXRhbCByZXdhcmQgdGhhdCBvdXRsaXZlcyB0aGUgcHJvZ3JhbS4="],
  [13, 25, "UGVyY3Vzc2l2ZSByZWNvdmVyeSB0b29sIGZ1bmQgKG9wdGlvbmFsKQ==", "Q29tZm9ydCB0b29sLCBub3QgYSBtYWdpYyByZWNvdmVyeSBkZXZpY2U7IGNoZWNrIGVsaWdpYmxlIGRpc2NvdW50cy4="],
  [14, 50, "TmF0dXJlIC8gc2hhcmVkIG91dGRvb3IgZGF5", "QSBtZW1vcmFibGUgcmV3YXJkIHRoYXQgYWxzbyBzZXJ2ZXMgcmVjb3Zlcnku"],
  [15, 25, "SG91c2UtaGFjayAvIGRvd24tcGF5bWVudCBkZXBvc2l0", "VHVybnMgaW1tZWRpYXRlIGRpc2NpcGxpbmUgaW50byBhIGxvbmdlci10ZXJtIGdvYWwu"],
  [16, 225, "Q2FiaW4gLyBvdXRkb29yIHdlZWtlbmQgZnVuZA==", "Q2VsZWJyYXRlIHRoZSBjYW1wYWlnbiBvciBiYW5rIHRoZSBlbnRpcmUgYW1vdW50IHRvd2FyZCB0aGUgaG91c2UgZnVuZC4="],
]);

export const CACHE_LINKS = Object.freeze({
  1: { label: "Official shoe details", url: "https://www.altrarunning.com/en-us/products/mens-experience-wild-3-al0a85u6", check: "Recheck fit, price, return policy, and current clinician/PT clearance before using on trails." },
  2: { label: "Compare fractional plates", url: "https://www.google.com/search?q=fractional+weight+plates+microloading", check: "Choose pairs that fit your bar and stay within the cache value." },
  3: { label: "Compare sleep masks", url: "https://www.google.com/search?q=best+blackout+sleep+mask+side+sleeper", check: "Prioritize full blackout, washability, and comfortable side-sleeping." },
  4: { label: "Compare sound blockers", url: "https://www.google.com/search?q=white+noise+machine+daytime+sleep+night+shift", check: "Check volume control, loop quality, and return policy." },
  5: { label: "Compare food systems", url: "https://www.google.com/search?q=food+scale+meal+prep+containers", check: "Buy only what removes friction from the seven-day protein log." },
  6: { label: "Compare blackout upgrades", url: "https://www.google.com/search?q=blackout+curtains+night+shift+sleep", check: "Measure the room and block edge leakage before buying extras." },
  7: { label: "Compare assist bands", url: "https://www.google.com/search?q=pull+up+assist+bands+set", check: "Inspect load ratings and replace damaged bands." },
  8: { label: "Compare trekking poles", url: "https://www.google.com/search?q=adjustable+trekking+poles+pair", check: "Match grip, adjustability, and post-op terrain progression." },
  9: { label: "Compare neutral handles", url: "https://www.google.com/search?q=rotating+neutral+grip+pulling+handle", check: "Prioritize a stable neutral wrist and equipment compatibility." },
  10: { label: "Choose time-saving help", url: "https://www.google.com/search?q=house+cleaning+meal+prep+service+near+me", check: "Use the value only for a service that genuinely buys back recovery time." },
  11: { label: "Choose approved recovery", url: "https://www.google.com/search?q=sports+massage+near+me", check: "Only book a service appropriate for your surgical and orthopedic history." },
  12: { label: "AACN course pricing", url: "https://www.aacn.org/education/online-courses/course-pricing-overview", check: "Verify the course supports your actual ICU pathway before paying." },
  13: { label: "Check nurse discount", url: "https://shop.id.me/stores/6631-therabody", check: "Recheck eligibility and compare the discounted total—not the advertised percentage." },
  14: { label: "Plan the outdoor day", url: "https://www.alltrails.com/", check: "Stay inside the current return-to-hiking restrictions." },
  15: { label: "Bank to house goal", url: "https://www.sofi.com/banking/savings-account/", check: "Transfer it to the designated house-hack/down-payment bucket." },
  16: { label: "Plan the final experience", url: "https://www.google.com/search?q=northern+california+cabin+weekend", check: "Book only after schedule, budget, and mobility needs are clear—or bank it." },
});

export const BADGES = Object.freeze([
  { id: "first-workout", group: "Discipline", icon: "I", name: "First Entry", description: "Complete one scheduled workout." },
  { id: "clean-week", group: "Discipline", icon: "IV", name: "Four-Day Standard", description: "Complete all four outcomes in one week." },
  { id: "protein-week", group: "Recovery", icon: "P", name: "Protein Pledge", description: "Log seven days and average the weekly protein target." },
  { id: "weight-week", group: "Recovery", icon: "W", name: "Scale Standard", description: "Record three standardized weigh-ins in one week." },
  { id: "green-session", group: "Readiness", icon: "G", name: "Green Light", description: "Complete a Green-readiness session." },
  { id: "yellow-discipline", group: "Readiness", icon: "Y", name: "Yellow Discipline", description: "Accept and complete an automatic Yellow adjustment." },
  { id: "red-discipline", group: "Readiness", icon: "R", name: "Red Means Recover", description: "Complete an approved Red substitute instead of forcing a heavy day." },
  { id: "backoff", group: "Judgment", icon: "−", name: "Backoff Honored", description: "Record a miss and obey the automatic backoff." },
  { id: "baseline-bound", group: "Lower", icon: "B", name: "Baseline Bound", description: "Establish the first clean, pain-controlled squat baseline." },
  { id: "review-sealed", group: "Discipline", icon: "S", name: "Ledger Sealed", description: "Seal one weekly review." },
  { id: "streak-2", group: "Streak", icon: "2", name: "Two-Week Chain", description: "Seal two successful weeks in a row." },
  { id: "streak-4", group: "Streak", icon: "4", name: "Block Complete", description: "Seal four successful weeks in a row." },
  { id: "streak-8", group: "Streak", icon: "8", name: "Halfway Unbroken", description: "Seal eight successful weeks in a row." },
  { id: "streak-12", group: "Streak", icon: "12", name: "Twelve-Week Forge", description: "Seal twelve successful weeks in a row." },
  { id: "streak-16", group: "Streak", icon: "16", name: "Campaign Complete", description: "Seal all sixteen successful weeks." },
  { id: "pull-100", group: "Pull-Up", icon: "100", name: "Century Block", description: "Complete 100 strict pull-ups in one density session." },
  { id: "pull-200", group: "Pull-Up", icon: "200", name: "Two Hundred", description: "Complete 200 strict pull-ups in one density session." },
  { id: "pull-300", group: "Pull-Up", icon: "300", name: "Bronze Hour", description: "Complete 300 strict pull-ups in 60 minutes." },
  { id: "pull-400", group: "Pull-Up", icon: "400", name: "Silver Hour", description: "Complete 400 strict pull-ups in 60 minutes." },
  { id: "pull-500", group: "Pull-Up", icon: "500", name: "Five Hundred", description: "Complete 500 strict pull-ups in 60 minutes." },
  ...GOALS.flatMap((goal) => goal.medals.map((medal) => ({
    id: `${goal.id}-${medal.tier.toLowerCase()}`,
    group: "Mission Medal",
    icon: medal.tier === "Gold" ? "G" : medal.tier === "Silver" ? "S" : "B",
    name: `${goal.short} · ${medal.tier}`,
    description: `Earn the verified ${medal.label} standard.`,
  }))),
]);

export const SOURCES = Object.freeze([
  { title: "ACSM 2026 resistance-training update", url: "https://acsm.org/resistance-training-guidelines-update-2026/", note: "Consistency, effort, progressive overload, and individualization." },
  { title: "ACSM Position Stand: resistance training prescription", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12965823/", note: "Evidence synthesis for strength, hypertrophy, power, and function." },
  { title: "Periodized vs non-periodized training meta-analysis", url: "https://pubmed.ncbi.nlm.nih.gov/35044672/", note: "Supports planned variation for strength outcomes." },
  { title: "Autoregulation systematic review and meta-analysis", url: "https://pubmed.ncbi.nlm.nih.gov/40791980/", note: "Supports RPE/RIR and readiness-informed load selection." },
  { title: "Training to failure meta-analysis", url: "https://pubmed.ncbi.nlm.nih.gov/33497853/", note: "Failure is not required for strength or hypertrophy adaptation." },
  { title: "Rest intervals and strength development", url: "https://pubmed.ncbi.nlm.nih.gov/28933024/", note: "Longer rests generally preserve heavy-set performance." },
  { title: "Deloading consensus", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10809978/", note: "Planned fatigue reduction while maintaining training exposure." },
  { title: "Tapering and maximal strength review", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7552788/", note: "Volume reduction can express strength while limiting fatigue." },
  { title: "Protein supplementation meta-analysis", url: "https://bjsm.bmj.com/content/52/6/376", note: "Protein supports resistance-training adaptations; personal needs still vary." },
  { title: "NIOSH sleep guidance for nurses", url: "https://www.cdc.gov/niosh/work-hour-training-for-nurses/longhours/mod9/05.html", note: "Sleep opportunity and shift-work recovery matter for readiness." },
  { title: "Criterion-based ACL reconstruction rehabilitation", url: "https://bjsm.bmj.com/content/57/9/500", note: "Lower-body progression should be criterion-led, not calendar-forced." },
]);

export const NAV_ITEMS = Object.freeze([
  { id: "today", label: "Today", icon: "01" },
  { id: "calendar", label: "Calendar", icon: "02" },
  { id: "goals", label: "Missions", icon: "03" },
  { id: "vault", label: "Vault", icon: "04" },
  { id: "review", label: "Review", icon: "05" },
  { id: "philosophy", label: "Method", icon: "06" },
  { id: "settings", label: "Settings", icon: "07" },
]);
